<?php

/**
 * PoiBase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    3epnmJunaio
 * @subpackage model
 * @author     Marcel Bretschneider
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPoiBase extends BasePoiBase
{
    public function getThumbnail() {
        if ($this->_get('thumbnail') != "")
            return "/uploads/thumbnails/".$this->_get('thumbnail');
        return "/sfJunaioBackendPlugin/images/numeric/red".sprintf("%02d", $this->_get('id')).".png";
    }
    public function getIcon() {
        if ($this->_get('icon') != "")
            return "/uploads/icons/".$this->_get('icon');
        return "/sfJunaioBackendPlugin/images/numeric/red".sprintf("%02d", $this->_get('id')).".png";
    }
}
